"""Generate runtime JSON and the English template from XLIFF 1.2. No dependencies."""
import argparse
import copy
import json
import re
import os
import tempfile
from pathlib import Path
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
SOURCES = ROOT / 'src/package/localization'
OUTPUT = ROOT / 'src/package/ui/locales'
TEMPLATE = ROOT / 'docs/localization/HapticAudioFeedback_template.xliff'


def catalog(path):
    root = ET.parse(path).getroot()
    for element in root.iter():
        if element.tag.startswith('{urn:oasis:names:tc:xliff:document:1.2}'):
            element.tag = element.tag.split('}', 1)[1]
    if root.tag != 'xliff' or root.get('version') != '1.2':
        raise ValueError(f'{path}: expected XLIFF 1.2')
    files = root.findall('file')
    languages = {f.get('target-language') for f in files}
    if len(languages) != 1:
        raise ValueError(f'{path}: every file must have the same target-language')
    language = languages.pop()
    if not language or not re.fullmatch(r'[a-z]{2}-[A-Z]{2}', language) or language == 'en-US':
        raise ValueError(f'{path}: expected a translation language such as de-DE')
    if path.name != f'HapticAudioFeedback_{language}.xliff':
        raise ValueError(f'{path}: filename must match target-language')
    result, seen, ids = {}, {}, set()
    for f in files:
        if f.get('source-language') != 'en-US':
            raise ValueError(f'{path}: source-language must remain en-US')
        for u in f.iter('trans-unit'):
            identity = (f.get('original'), u.get('id'))
            if not u.get('id') or identity in ids:
                raise ValueError(f'{path}: missing or duplicate unit ID')
            ids.add(identity)
            source, target = u.find('source'), u.find('target')
            if source is None or not source.text or len(source) or (target is not None and len(target)):
                raise ValueError(f'{path}: plain-text source/target required')
            key = source.text
            value = target.text if target is not None and target.text else key
            if key in seen and seen[key] != value:
                raise ValueError(f'{path}: conflicting translations for {key!r}')
            seen[key] = value
            result[key] = value
    if not result:
        raise ValueError(f'{path}: empty catalog')
    return language, result, root


def outputs():
    generated = {}
    sources = sorted(SOURCES.glob('HapticAudioFeedback_*.xliff'))
    if not sources:
        raise ValueError('No translation sources found')
    languages = []
    reference = None
    for path in sources:
        language, strings, root = catalog(path)
        languages.append(language)
        generated[OUTPUT / f'{language}.json'] = json.dumps(strings, ensure_ascii=False, indent=2) + '\n'
        if language == 'zh-CN':
            reference = root
    generated[OUTPUT / 'available.js'] = '// Generated by tools/generate_localization.py; edit XLIFF, not this file.\nconst availableLocales=' + json.dumps(['en'] + languages) + ';\n'
    if reference is not None:
        template = copy.deepcopy(reference)
        for f in template.findall('file'):
            f.set('target-language', 'REPLACE-ME')
        for u in template.iter('trans-unit'):
            target = u.find('target')
            if target is None:
                target = ET.SubElement(u, 'target')
            target.text = None
            target.set('state', 'needs-translation')
        ET.indent(template, space='  ')
        generated[TEMPLATE] = '<?xml version="1.0" encoding="utf-8"?>\n' + ET.tostring(template, encoding='unicode') + '\n'
    return generated


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if generated files are stale')
    args = parser.parse_args()
    stale = []
    generated = outputs()
    for path in OUTPUT.glob('*.json'):
        if re.fullmatch(r'[a-z]{2}-[A-Z]{2}\.json', path.name) and path not in generated:
            if args.check:
                stale.append(str(path.relative_to(ROOT)))
            else:
                path.unlink()  # Only generated locale names within OUTPUT.
    for path, text in generated.items():
        if path.exists() and path.read_text(encoding='utf-8') == text:
            continue
        if args.check:
            stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            with tempfile.NamedTemporaryFile(mode='w', encoding='utf-8', newline='\n', dir=path.parent, delete=False) as output:
                output.write(text)
                temporary = output.name
            os.replace(temporary, path)
    if stale:
        raise SystemExit('Regenerate translations: ' + ', '.join(stale))
    print('PASS XLIFF catalogs and template are current')

if __name__ == '__main__':
    main()
